DROP DATABASE WALMARTDESAFIO;
CREATE DATABASE WALMARTDESAFIO;
USE WALMARTDESAFIO;

CREATE TABLE CLIENTE (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL ,
	idade INT,
	sexo VARCHAR(1),
	PRIMARY KEY (id)
);

CREATE TABLE PAIS(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE ESTADO(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	id_pais INT,
	FOREIGN KEY (id_pais) REFERENCES PAIS (id),
	PRIMARY KEY (id)
);
CREATE TABLE CIDADE(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	id_estado INT,
	id_pais INT,
	FOREIGN KEY (id_pais) REFERENCES PAIS (id),
	FOREIGN KEY (id_estado) REFERENCES ESTADO (id),
	PRIMARY KEY (id)
);

CREATE TABLE ENDERECO(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	lugarejo VARCHAR(255) NOT NULL,
	CEP INT,
	id_cidade INT,
	id_estado INT,
	id_pais INT,
	id_cliente INT,
	FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id),
	FOREIGN KEY (id_pais) REFERENCES PAIS (id),
	FOREIGN KEY (id_estado) REFERENCES ESTADO (id),
	FOREIGN KEY (id_cidade) REFERENCES CIDADE (id),
	PRIMARY KEY (id)
);

CREATE TABLE PRODUTO(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	preco DOUBLE,
	quantidade INT,
	PRIMARY KEY (id)
);

CREATE TABLE PEDIDO(
	id INT AUTO_INCREMENT,
	id_cliente INT,
	id_produto INT,
	id_endereco INT,
	total DOUBLE,
	data DATE,
	PRIMARY KEY (id),
	FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id),
	FOREIGN KEY (id_produto) REFERENCES PRODUTO (id),
	FOREIGN KEY (id_endereco) REFERENCES ENDERECO (id)
);

INSERT INTO PAIS (nome) VALUES ("Brasil");
INSERT INTO PAIS (nome) VALUES ("Chile");
INSERT INTO PAIS (nome) VALUES ("Argentina");

INSERT INTO ESTADO (nome, id_pais) VALUES ("SP", 1);
INSERT INTO ESTADO (nome, id_pais) VALUES ("RJ", 1);
INSERT INTO ESTADO (nome, id_pais) VALUES ("MG", 1);

INSERT INTO CIDADE (nome, id_pais, id_estado) VALUES ("Santos", 1, 1);
INSERT INTO CIDADE (nome, id_pais, id_estado) VALUES ("Petropolis", 1, 2);
INSERT INTO CIDADE (nome, id_pais, id_estado) VALUES ("Belo Horizonte", 1, 3);

SELECT C.nome, E.nome, P.nome 
FROM CIDADE C, ESTADO E, PAIS P 
WHERE C.id_estado = E.id and P.id = E.id_pais;
